jwt:
  secret:
    key: aLongSecretStringWhoseBitnessIsEqualToOrGreaterThanTheBitnessOfTheTokenEncryptionAlgorithm
  expiration: 86400000

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  flyway:
    baselineOnMigrate: true

server:
  error:
    include-stacktrace: never
