spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: SuperPassword@22
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  flyway:
    baselineOnMigrate: true

server:
  error:
    include-stacktrace: never
