spring:
  profiles:
    active: qa

jwt:
  secret:
    key: aLongSecretStringWhoseBitnessIsEqualToOrGreaterThanTheBitnessOfTheTokenEncryptionAlgorithm
  expiration: 86400000

server:
  error:
    include-stacktrace: never