spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_flex_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
